export const TOGGLE_PAUSE = 'TOGGLE_PAUSE';
export const INCREMENT_INTERVAL_COUNT = 'INCREMENT_INTERVAL_COUNT';
export const RESET_SETTINGS = 'RESET_SETTINGS';
export const INCREMENT_REEF_HOLES = 'INCREMENT_REEF_HOLES';
export const DECREMENT_REEF_HOLES = 'DECREMENT_REEF_HOLES';
