export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const INCREMENT_INTERVAL_COUNT = 'INCREMENT_INTERVAL_COUNT';
export const RESET_SETTINGS = 'RESET_SETTINGS';
export const SET_MODE = 'SET_MODE';
export const SET_ANIMATION_INDEX = 'SET_ANIMATION_INDEX';
export const TOGGLE_ANIMATION_IN_MOTION = 'TOGGLE_ANIMATION_IN_MOTION';
export const TOGGLE_SHOW_SCALE = 'TOGGLE_SHOW_SCALE';
export const SET_DISTRIBUTION = 'SET_DISTRIBUTION';
export const SET_SLIDER_CARBON_DIOXIDE = 'SET_SLIDER_CARBON_DIOXIDE';
export const SET_EQUILIBRIUM_CARBON_DIOXIDE = 'SET_EQUILIBRIUM_CARBON_DIOXIDE';
export const SET_DISEQUILIBRIUM_CYCLES_BEGIN_AT =
  'SET_DISEQUILIBRIUM_CYCLES_BEGIN_AT';
export const SET_INTERVAL_COUNT_DIRECTLY = 'SET_INTERVAL_COUNT_DIRECTLY';
export const SET_PH_CARBON_DIOXIDE = 'SET_PH_CARBON_DIOXIDE';
export const SET_CARBON_DIOXIDE_CHANGE = 'SET_CARBON_DIOXIDE_CHANGE';
export const SET_YEAR = 'SET_YEAR';
